import type { ServiceContent } from "./ServicePage";

export const services: Record<string, ServiceContent> = {
  interior: {
    slug: "interior-painting", name: "Interior Painting", shortName: "Interior painting", eyebrow: "Interior painting",
    description: "Professional interior painting for Phoenix-area homes, with careful protection, surface preparation, clean lines, and a finish selected for how each room is used.", image: "/collov-home-design-UUsQk_9bdR8-unsplash.jpg",
    benefits: [{ title: "Protection first", text: "Floors, furniture, fixtures, and adjacent surfaces are protected before preparation begins." }, { title: "Surface-specific prep", text: "Holes, cracks, stains, and problem areas are addressed before paint is applied." }, { title: "The right finish", text: "We help match color and sheen to the room, lighting, traffic, and cleaning needs." }],
    process: [{ title: "Walkthrough and scope", text: "We inspect the rooms, discuss goals, and define exactly what will be painted." }, { title: "Protect and prepare", text: "The work area is covered, repaired, cleaned, sanded, and primed as needed." }, { title: "Apply and inspect", text: "Coatings are applied evenly, details are checked, and the site is kept orderly." }, { title: "Final walkthrough", text: "We review the work with you and address agreed touch-ups before completion." }],
    faqs: [["Do I need to move my furniture?", "We will explain what should be moved before the project. Larger items can often be shifted and carefully protected in place."], ["Can you help choose colors and sheens?", "Yes. We can help narrow the choices based on lighting, existing finishes, room use, and maintenance needs."], ["Can I remain in my home during painting?", "Often, yes. The answer depends on the scope, ventilation, products selected, and your household’s needs."], ["Which paint brands do you use?", "We work with professional Sherwin-Williams and Dunn-Edwards coating systems selected for the surface and project." ]],
  },
  exterior: {
    slug: "exterior-painting", name: "Exterior Painting", shortName: "Exterior painting", eyebrow: "Arizona exterior painting",
    description: "Exterior painting for Phoenix-area homes using preparation and coating systems designed around intense sun, heat, dust, and changing Arizona weather.", image: "/exterior.png",
    benefits: [{ title: "Arizona-aware preparation", text: "Chalking, cracking, peeling, and failed sealant are identified before coating begins." }, { title: "Durable coating systems", text: "Products are chosen for the surface, exposure, color, and expected Arizona conditions." }, { title: "Respect for your property", text: "Windows, fixtures, hardscape, roofing, and landscaping are protected throughout the work." }],
    process: [{ title: "Exterior inspection", text: "We inspect stucco, wood, metal, trim, fascia, doors, and other included surfaces." }, { title: "Wash and repair", text: "Surfaces are cleaned and failing material, cracks, gaps, and damaged areas are addressed as scoped." }, { title: "Prime and paint", text: "Bare or problem areas are primed as required before the finish coats are applied." }, { title: "Detail review", text: "Protection is removed, the site is cleaned, and the completed work is reviewed with you." }],
    faqs: [["How often should an Arizona home be repainted?", "Timing varies by coating quality, color, exposure, substrate, and previous preparation. A site inspection is the best way to judge condition."], ["Do you repair stucco cracks?", "Minor crack and surface preparation can be included in the written scope. Structural or extensive repairs may require a specialist."], ["Can you work with HOA color requirements?", "Yes. Provide the approved palette or HOA documentation and we can build the estimate around the permitted colors."], ["Do you paint doors, gates, and fascia?", "They can be included. Your written estimate will identify every included surface so the scope is clear." ]],
  },
  cabinets: {
    slug: "cabinet-refinishing", name: "Cabinet Refinishing", shortName: "Cabinet refinishing", eyebrow: "Kitchen cabinet refinishing",
    description: "Cabinet refinishing for Phoenix-area kitchens and built-ins, with detailed cleaning, preparation, and professional coating application for a durable updated finish.", image: "/kitchen.png",
    benefits: [{ title: "Detailed preparation", text: "Doors, drawers, boxes, and frames are cleaned, deglossed, repaired, and prepared for adhesion." }, { title: "Controlled application", text: "The coating process is planned to produce a smooth, consistent finish while protecting the surrounding kitchen." }, { title: "A practical transformation", text: "Update the color and feel of the room without replacing a functional cabinet layout." }],
    process: [{ title: "Cabinet assessment", text: "We inspect the cabinet material, condition, finish, hardware, and desired color." }, { title: "Label and protect", text: "Components are organized and the kitchen is carefully masked and protected." }, { title: "Prep and coat", text: "Surfaces are cleaned and prepared before the selected primer and finish system is applied." }, { title: "Reassemble and review", text: "Doors and drawers are reinstalled, alignment is checked, and the finish is reviewed with you." }],
    faqs: [["Is refinishing cheaper than replacing cabinets?", "It is often more economical when the existing boxes and layout are in good condition, but the exact comparison depends on the project."], ["How durable is a painted cabinet finish?", "Durability depends on preparation, product selection, application, cure time, and normal care. We recommend a system built for cabinet use."], ["Can you change the hardware?", "Hardware replacement can be discussed during the estimate. New hole spacing or concealed-hinge changes may require additional carpentry."], ["How long before cabinets can be used normally?", "Dry and cure times differ. We will provide product-specific handling and care guidance for your project." ]],
  },
  epoxy: {
    slug: "epoxy-floor-coatings", name: "Epoxy Floor Coatings", shortName: "Epoxy flooring", eyebrow: "Garage floor coatings",
    description: "Garage floor coating systems for Phoenix-area properties, with concrete preparation, repair planning, decorative finish options, and straightforward care guidance.", image: "/epoxy.png",
    benefits: [{ title: "Concrete evaluation", text: "The slab is checked for condition, contamination, cracks, previous coatings, and moisture concerns." }, { title: "Mechanical preparation", text: "The preparation method is matched to the slab and selected coating system for reliable adhesion." }, { title: "Purpose-built finish", text: "Color, texture, traction, UV exposure, and maintenance needs are considered before installation." }],
    process: [{ title: "Inspect the slab", text: "We review the concrete, drainage, joints, damage, and current coating or sealer." }, { title: "Prepare and repair", text: "The slab is mechanically prepared and repairs are completed according to the agreed scope." }, { title: "Install the system", text: "Coating layers, decorative media, and topcoat are installed according to the selected system." }, { title: "Cure and care", text: "We explain cure time, return-to-service timing, cleaning, and long-term care." }],
    faqs: [["Is every garage slab suitable for coating?", "No. Moisture, contamination, concrete condition, and previous treatments can affect suitability. We inspect before recommending a system."], ["Will the floor be slippery?", "Texture and traction options can be discussed based on how the space is used and the appearance you want."], ["How long until I can park on it?", "Return-to-service time depends on the exact product, temperature, and conditions. We provide project-specific guidance."], ["Can cracks be repaired first?", "Many non-structural cracks and surface defects can be addressed, but movement can cause repaired cracks to reappear." ]],
  },
  commercial: {
    slug: "commercial-painting", name: "Commercial Painting", shortName: "Commercial painting", eyebrow: "Commercial properties",
    description: "Interior and exterior commercial painting for Phoenix-area offices, retail spaces, multifamily properties, and managed facilities, with a clearly defined scope and scheduling plan.", image: "/slidebean-TpGIpUF67po-unsplash.jpg",
    benefits: [{ title: "Defined scope", text: "Included surfaces, preparation, products, access, schedule, and exclusions are documented before work begins." }, { title: "Scheduling coordination", text: "Work is planned around occupants, customers, operating hours, access, and other trades." }, { title: "Consistent communication", text: "A clear point of contact and progress updates keep owners and managers informed." }],
    process: [{ title: "Site walk", text: "We inspect the property, discuss operational constraints, and document the requested work." }, { title: "Scope and schedule", text: "We prepare a clear proposal covering surfaces, preparation, products, phasing, and timing." }, { title: "Coordinated production", text: "The work area, access, protection, and daily communication are managed around the property." }, { title: "Completion review", text: "We conduct a final walkthrough and close out the documented scope." }],
    faqs: [["Can work be scheduled around business hours?", "Depending on the project, work may be phased or scheduled to reduce disruption. Scheduling requirements should be discussed during the site walk."], ["Do you handle occupied properties?", "Yes, when the scope and conditions allow. Protection, access, communication, and occupant impact are planned before work begins."], ["Can you provide a detailed written proposal?", "Yes. Commercial proposals should clearly identify included surfaces, preparation, products, quantities or areas, exclusions, and scheduling assumptions."], ["What types of commercial properties do you paint?", "We can evaluate offices, retail spaces, multifamily properties, common areas, and other managed facilities throughout the Phoenix area." ]],
  },
};
