import type { ServiceContent } from "./ServicePage";

export const services: Record<string, ServiceContent> = {
  interior: {
    slug: "interior-painting", name: "Interior Painting", shortName: "Interior painting", eyebrow: "Phoenix interior painting",
    description: "Professional interior painting for Phoenix-area homes, built around careful protection, surface-specific preparation, clean lines, and coating systems selected for how each room is actually used.", image: "/collov-home-design-UUsQk_9bdR8-unsplash.jpg",
    localNote: "Arizona homes bring their own interior challenges—from intense natural light that exposes wall imperfections to dust, high-traffic living spaces, and finishes that need to stand up to everyday cleaning. We build the scope around the actual room and surface rather than using one generic paint specification.",
    benefits: [{ title: "Protection before production", text: "Floors, furniture, fixtures, cabinets, and adjacent surfaces are protected before preparation or coating begins." }, { title: "Prep matched to the surface", text: "Holes, cracks, stains, previous repairs, sheen changes, and problem areas are evaluated so the proposal defines the preparation that is actually needed." }, { title: "Finish selected for real life", text: "Color, sheen, washability, traffic, lighting, and room use are considered before the coating system is selected." }],
    process: [{ title: "Walkthrough and written scope", text: "We inspect the rooms, identify included surfaces, discuss colors and use, and document what will and will not be painted." }, { title: "Protect and prepare", text: "The work area is protected and included surfaces are cleaned, repaired, sanded, caulked, or primed as required by the written scope." }, { title: "Professional application", text: "The selected coating system is applied to the specified surfaces with attention to clean lines, consistent finish, and an orderly jobsite." }, { title: "Final quality walkthrough", text: "We review the completed work against the written scope with you and address agreed punch-list items before closeout." }],
    packageNote: "When multiple specifications make sense, your proposal can present Essential, Signature, and Premier options so you can compare preparation, coating choices, protection, warranty, and investment. Warranty length depends on the selected package and covered surface, with eligible Premier projects offering up to an 8-year limited workmanship warranty.",
    faqs: [["Do I need to move my furniture?", "We will explain what should be moved before the project. Larger items can often be shifted and carefully protected in place."], ["Can you help choose colors and sheens?", "Yes. We can help narrow the choices based on lighting, existing finishes, room use, washability, and maintenance needs."], ["Can I remain in my home during painting?", "Often, yes. The answer depends on the scope, ventilation, products selected, scheduling, and your household’s needs."], ["Which paint brands do you use?", "We work with professional Sherwin-Williams and Dunn-Edwards coating systems selected for the surface and project."], ["Is there a workmanship warranty?", "Eligible projects include a limited Color Rise workmanship warranty. The applicable term depends on the selected package and covered surface, with Premier offering up to 8 years where eligible."]]
  },
  exterior: {
    slug: "exterior-painting", name: "Exterior Painting", shortName: "Exterior painting", eyebrow: "Arizona exterior painting",
    description: "Exterior painting for Phoenix-area homes using preparation and coating systems selected around intense UV, heat, dust, stucco conditions, exposure, and the demands of the Arizona climate.", image: "/exterior.png",
    localNote: "Phoenix exteriors are punished by intense UV, heat, windblown dust, monsoon weather, chalking, failed sealants, and movement in stucco and trim. Long-term performance starts with diagnosing those conditions before a coating is selected.",
    benefits: [{ title: "Arizona-aware preparation", text: "We look for chalking, cracking, peeling, failed sealant, bare substrate, moisture indicators, and other conditions that can undermine a new coating." }, { title: "Coating system matched to exposure", text: "Product selection considers substrate, existing condition, color, sun exposure, sheen, and the level of protection selected in your proposal." }, { title: "HOA and property protection", text: "Approved color requirements can be incorporated into the scope, while windows, fixtures, roofing, hardscape, vehicles, and landscaping are protected during production." }],
    process: [{ title: "Exterior condition assessment", text: "We inspect included stucco, siding, wood, metal, fascia, trim, doors, gates, and other surfaces and document visible problem areas." }, { title: "Clean, protect, and prepare", text: "Surfaces are cleaned as appropriate and included cracks, failed coating, gaps, bare areas, and other preparation items are addressed according to the selected scope." }, { title: "Prime and apply the selected system", text: "Bare or problem areas are primed where required and the specified professional coating system is applied to the included surfaces." }, { title: "Detail review and final walkthrough", text: "Protection is removed, the site is cleaned, details are reviewed, and we walk the completed written scope with you before closeout." }],
    packageNote: "Exterior proposals can be built around Essential, Signature, and Premier protection systems. For Sherwin-Williams exterior projects, our current package ladder can include SuperPaint® for Essential, Latitude® for Signature, and Duration® for Premier when those products are appropriate for the substrate and project. Eligible Premier covered surfaces can receive up to an 8-year limited workmanship warranty.",
    faqs: [["How often should an Arizona home be repainted?", "Timing varies by coating quality, color, orientation, sun exposure, substrate, previous preparation, and existing condition. A site inspection is the best way to determine whether the coating system is still protecting the home."], ["Do you repair stucco cracks?", "Minor non-structural crack preparation can be included in the written scope. Structural movement, recurring cracks, substrate failure, or extensive stucco repair may require additional scope or a specialist."], ["Can you work with HOA color requirements?", "Yes. Provide the approved palette or HOA documentation and we can build the proposal around permitted colors and required approvals."], ["Do you pressure wash before painting?", "Exterior surfaces are cleaned using a method appropriate to the substrate and condition. The goal is a sound surface for preparation and coating, not a one-size-fits-all washing step."], ["Do you paint doors, gates, fascia, and trim?", "They can be included. Your written proposal identifies the exact surfaces, preparation, coating system, and exclusions so there is no ambiguity."], ["What is the Premier warranty?", "Eligible Premier projects can include up to an 8-year limited Color Rise workmanship warranty on covered surfaces. The written warranty defines the applicable term, eligibility requirements, conditions, and exclusions."]]
  },
  cabinets: {
    slug: "cabinet-refinishing", name: "Cabinet Refinishing", shortName: "Cabinet refinishing", eyebrow: "Kitchen cabinet refinishing",
    description: "Professional cabinet refinishing for Phoenix-area kitchens and built-ins, with a process focused on adhesion, controlled preparation, smooth application, cure, and protection of the surrounding home.", image: "/kitchen.png",
    localNote: "Cabinet refinishing is not wall painting. Oils, cleaners, existing finishes, edge wear, hardware, substrate type, and cure requirements all affect adhesion and durability. The system has to be built around the cabinet in front of us.",
    benefits: [{ title: "Adhesion starts with preparation", text: "Doors, drawers, frames, and boxes are evaluated, cleaned, deglossed, repaired, sanded, and primed as required by the selected system." }, { title: "Controlled application", text: "Masking, component organization, coating selection, and application are planned to create a consistent furniture-like finish while protecting the surrounding kitchen." }, { title: "Durability and cure matter", text: "The proposal considers coating durability, normal kitchen use, cure time, handling, and care—not just the color you see on day one." }],
    process: [{ title: "Cabinet assessment and scope", text: "We inspect material, existing finish, damage, hardware, layout, desired color, and which components are included." }, { title: "Label, protect, and prepare", text: "Components are organized, surrounding areas are protected, and included surfaces are cleaned and prepared for the selected primer and finish system." }, { title: "Prime and finish", text: "The specified coating system is applied under a controlled process designed for adhesion, consistency, and the selected finish." }, { title: "Reassemble, cure guidance, and review", text: "Components are reinstalled, alignment and finish are checked, and you receive handling and cure guidance before normal use." }],
    packageNote: "Where multiple cabinet systems are appropriate, we can present Essential, Signature, and Premier options so the differences in preparation, coating system, protection, warranty, and investment are clear. Cabinet warranty eligibility and term depend on the selected system and covered surfaces.",
    faqs: [["Is refinishing cheaper than replacing cabinets?", "It is often more economical when the existing boxes, doors, and layout are in suitable condition, but the exact comparison depends on the project and desired changes."], ["How durable is a refinished cabinet?", "Durability depends heavily on cleaning, preparation, primer and finish compatibility, application, cure time, and normal care. We specify coating systems intended for cabinet use."], ["Can you change the hardware?", "Hardware replacement can be discussed during the estimate. New hole spacing, concealed-hinge conversions, carpentry, or door modifications may require additional scope."], ["How long before cabinets can be used normally?", "Dry and cure times are not the same. We provide product- and project-specific guidance for light handling and return to normal use."], ["Are all cabinets good candidates for refinishing?", "No. Material, existing finish, contamination, damage, delamination, and previous coatings can affect suitability. We evaluate the cabinets before recommending a system."]]
  },
  epoxy: {
    slug: "epoxy-floor-coatings", name: "Garage Floor Coatings", shortName: "Garage floor coatings", eyebrow: "Phoenix garage floor coatings",
    description: "Garage floor coating systems for Phoenix-area properties, built around concrete evaluation, mechanical preparation, repair planning, UV exposure, traction, cure, and return-to-service requirements.", image: "/epoxy.png",
    localNote: "Phoenix garages see hot tires, intense slab temperatures, dust, automotive fluids, and strong UV near open garage doors. A durable floor starts with the concrete condition and preparation—not the decorative flakes.",
    benefits: [{ title: "Concrete first", text: "We evaluate slab condition, contamination, cracks, joints, previous coatings or sealers, and visible moisture concerns before recommending a system." }, { title: "Mechanical preparation", text: "The slab preparation method is selected to create the surface profile required by the coating system rather than relying on cosmetic cleaning alone." }, { title: "System built for the space", text: "Color, decorative media, traction, UV exposure, topcoat, maintenance, and return-to-service needs are considered before installation." }],
    process: [{ title: "Inspect and qualify the slab", text: "We review the concrete, drainage, joints, damage, contamination, existing coatings, and conditions that could affect adhesion." }, { title: "Mechanically prepare and repair", text: "The slab is prepared and included non-structural repairs are completed according to the written scope and selected system." }, { title: "Install the coating system", text: "Primer/base layers, decorative media, and topcoat are installed according to the specified system and site conditions." }, { title: "Cure, care, and final review", text: "We explain cure and return-to-service timing, cleaning and maintenance, then review the completed scope before closeout." }],
    packageNote: "Garage coating proposals are specified around the slab and intended use. Where multiple systems make sense, Essential, Signature, and Premier options can make the differences in preparation, build, UV protection, topcoat, warranty, and investment easy to compare.",
    faqs: [["Is every garage slab suitable for coating?", "No. Moisture, contamination, concrete condition, movement, previous treatments, and existing coatings can affect suitability. We inspect before recommending a system."], ["Will the floor be slippery?", "Traction can be adjusted through the selected texture and system. We discuss appearance, cleaning, and how the space is used before specifying the finish."], ["How long until I can park on it?", "Return-to-service time depends on the exact coating system, temperature, conditions, and manufacturer requirements. We provide project-specific guidance."], ["Can cracks be repaired first?", "Many non-structural cracks and surface defects can be addressed, but concrete movement can cause repaired cracks to reappear and structural movement is not eliminated by a coating."], ["Why is mechanical preparation important?", "A coating system is only as reliable as its bond to the concrete. Proper surface profiling helps remove weak surface material and creates the condition required for adhesion."]]
  },
  commercial: {
    slug: "commercial-painting", name: "Commercial Painting", shortName: "Commercial painting", eyebrow: "Phoenix commercial painting",
    description: "Interior and exterior commercial painting for Phoenix-area offices, retail spaces, multifamily properties, common areas, and managed facilities, with documented scope, phasing, access, communication, and closeout.", image: "/slidebean-TpGIpUF67po-unsplash.jpg",
    localNote: "Commercial painting succeeds or fails on planning as much as application. Access, occupants, operating hours, tenant communication, phasing, safety, other trades, and completion standards need to be defined before production starts.",
    benefits: [{ title: "Scope before production", text: "Included surfaces, preparation, products, access, schedule assumptions, phasing, exclusions, and responsible parties are documented before work begins." }, { title: "Operational coordination", text: "Work can be planned around customers, tenants, employees, operating hours, access restrictions, and other trades when the project allows." }, { title: "Accountable communication", text: "A defined point of contact, progress communication, documented changes, and completion review help owners and managers stay informed." }],
    process: [{ title: "Site walk and requirements", text: "We inspect the property, identify requested surfaces, and document access, operating, occupant, phasing, and scheduling constraints." }, { title: "Written scope and production plan", text: "The proposal defines preparation, products, areas, exclusions, assumptions, phasing, and scheduling requirements before work begins." }, { title: "Coordinated production", text: "Protection, access, work areas, communication, and documented changes are managed around the property and agreed plan." }, { title: "Punch list and closeout", text: "We review the documented scope, address agreed punch-list items, complete cleanup, and close out the project with the designated contact." }],
    packageNote: "Commercial work is specified to the property rather than forced into a residential package. When tiered options are useful, we can still present Essential, Signature, and Premier alternatives so decision-makers can compare preparation, products, service level, warranty, and investment.",
    faqs: [["Can work be scheduled around business hours?", "Depending on the project, work may be phased or scheduled to reduce disruption. Access, noise, cure times, lighting, and building requirements are discussed during planning."], ["Do you handle occupied properties?", "Yes, when the scope and conditions allow. Protection, access, communication, occupant impact, and sequencing are planned before work begins."], ["Can you provide a detailed written proposal?", "Yes. Commercial proposals identify included surfaces, preparation, products, exclusions, access and scheduling assumptions, and other project-specific requirements."], ["What types of commercial properties do you paint?", "We can evaluate offices, retail spaces, multifamily properties, common areas, managed facilities, and other suitable commercial properties throughout the Phoenix metro area."], ["How are changes handled?", "Changes to the agreed scope should be documented and approved before the additional work proceeds so schedule, responsibility, and price remain clear."]]
  },
};
